version: "3.9"

services:
    kong-database:
        image: postgres:9.6
        container_name: kong-database
        networks:
            - kong-micro
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-d",
                    "${KONG_PG_DATABASE:-kong}",
                    "-U",
                    "${KONG_PG_USER:-kong}",
                ]
            interval: 30s
            timeout: 30s
            retries: 3
        restart: on-failure

    kong:
        build:
            context: ./kong
        image: kong-custom
        container_name: kong
        networks:
            - kong-micro
        ports:
            - "8000:8000"
            - "8443:8443"
            - "127.0.0.1:8001:8001"
            - "127.0.0.1:8444:8444"
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_PASSWORD: kong
            KONG_CASSANDRA_CONTACT_POINTS: kong-database
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        depends_on:
            - kong-database
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 10s
            timeout: 10s
            retries: 10
        restart: on-failure:5

    test-rest:
        build:
            context: ./testRest
            dockerfile: Dockerfile
        container_name: testRest
        networks:
            - kong-micro
        ports:
            - "3000:3000"
        depends_on:
            - kong

    # mysql:
    #     build:
    #         context: ./mysql
    #         dockerfile: Dockerfile
    #     container_name: mysql
    #     networks:
    #         - kong-micro
    #     ports:
    #         - "3306:3306"
    #     # ENV MYSQL_ROOT_PASSWORD=123456
    #     # ENV MYSQL_DATABASE=testdb
    #     # ENV MYSQL_USER=root
    #     # ENV MYSQL_PASSWORD=123456
    #     # ENV MYSQL_HOST=localhost
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 123456
    #         MYSQL_DATABASE: testdb
    #         MYSQL_USER: root
    #         MYSQL_PASSWORD: 123456
    # rest:
    #     build:
    #         context: ./rest
    #         dockerfile: Dockerfile
    #     container_name: rest
    #     networks:
    #         - kong-micro
    #     ports:
    #         - "6969:6969"
    #     depends_on:
    #         - mysql

networks:
    kong-micro:
        driver: bridge
